package com.payment;

/**
 * Generates internal Student Record Numbers in the format STU-000001.
 *
 * IMPORTANT: This is NOT an official university Student ID.
 * The source Excel files do NOT contain official Student IDs.
 * This is an internal identifier generated by the application.
 */
public final class StudentCodeGenerator {

    private static final String PREFIX = "STU-";
    private static final int CODE_LENGTH = 6; // STU-000001

    private StudentCodeGenerator() {}

    /**
     * Generate a student record number from a numeric sequence.
     *
     * @param sequence 1-based sequence number
     * @return Formatted student code, e.g., "STU-000001"
     */
    public static String generate(int sequence) {
        if (sequence < 0) sequence = 0;
        String num = String.format("%0" + CODE_LENGTH + "d", sequence);
        return PREFIX + num;
    }

    /**
     * Extract the numeric sequence from a student code.
     *
     * @param code Student code (e.g., "STU-000042")
     * @return Sequence number, or -1 if invalid format
     */
    public static int extractSequence(String code) {
        if (code == null || !isValidFormat(code)) return -1;
        try {
            return Integer.parseInt(code.substring(PREFIX.length()));
        } catch (NumberFormatException e) {
            return -1;
        }
    }

    /**
     * Get the next sequence number from a set of existing codes.
     *
     * @param existingCodes Array of existing student codes
     * @return Next sequence number (max + 1, or 1 if none)
     */
    public static int nextSequence(String[] existingCodes) {
        int max = 0;
        for (String code : existingCodes) {
            int seq = extractSequence(code);
            if (seq > max) max = seq;
        }
        return max + 1;
    }

    public static boolean isValidFormat(String code) {
        return code != null && code.matches("^STU-\\d{6}$");
    }
}